-- PM26 P06b-H -- reproduccion del subconjunto exacto de esquema QA
-- (columnas, PK, FKs, politicas RLS vigentes byte a byte) necesario
-- para validar la migracion 20260909200730_pm26_p06b_rendimiento_indices_rls_initplan.sql
-- en un Postgres local aislado, sin tocar QA. Solo para pruebas.

-- Un Postgres generico (p.ej. el paquete "postgresql" de Ubuntu en un
-- runner de CI) no trae los roles "anon"/"authenticated" de Supabase
-- por defecto -- se crean aqui si faltan, de forma idempotente.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated;
  end if;
end
$$;

create schema if not exists auth;
create table if not exists auth.users (id uuid primary key);

-- Simula auth.uid() leyendo una variable de sesion, para poder cambiar
-- de identidad dentro de la misma conexion de prueba. Null-safe, igual
-- que el auth.uid() real de Supabase cuando no hay JWT.
create or replace function auth.uid() returns uuid
language sql stable as $$
  select nullif(current_setting('app.current_uid', true), '')::uuid;
$$;

create schema if not exists private;

create table if not exists public.membresias_usuario (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  empresa_id text not null,
  local_id text,
  todos_locales boolean not null default false,
  rol text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.membresias_usuario enable row level security;

create table if not exists public.empleados (
  id text primary key,
  empresa_id text not null,
  local_id text not null,
  estado text not null default 'activo'
);

create table if not exists public.perfiles (
  user_id uuid primary key,
  rol text not null default 'Básico',
  empleado_id text references public.empleados(id),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.perfiles enable row level security;

create table if not exists public.suscripciones_push (
  endpoint text primary key,
  p256dh text not null,
  auth text not null,
  dispositivo text,
  creado_en timestamptz not null default now(),
  user_id uuid,
  local_id text
);
alter table public.suscripciones_push enable row level security;

create table if not exists public.stock_operaciones (
  operation_id text primary key
);

create table if not exists public.movimientos_stock (
  id bigint generated by default as identity primary key,
  operation_id text not null references public.stock_operaciones(operation_id),
  tipo text not null,
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.auditoria_registro (
  id text primary key,
  fecha date not null,
  datos jsonb,
  creado_en timestamptz not null default now(),
  empresa_id text,
  local_id text,
  actor_user_id uuid references auth.users(id)
);

create table if not exists public.pagos_encargo (
  id text primary key,
  operation_id text not null unique,
  encargo_id text not null,
  empresa_id text not null,
  local_id text not null,
  revierte_pago_id text references public.pagos_encargo(id)
);

-- Copia literal de la definicion vigente en QA de este helper (no se
-- toca en esta migracion; se reproduce aqui solo porque
-- membresia_propia_select depende de el).
create or replace function private.la_usuario_activo() returns boolean
language sql stable security definer
set search_path to 'public', 'auth', 'private', 'pg_temp'
as $$
  select exists (
    select 1
      from public.perfiles p
     where p.user_id = auth.uid()
       and p.activo = true
       and (
         (
           p.empleado_id is null
           and exists (
             select 1
               from public.membresias_usuario m
              where m.user_id = p.user_id
                and m.activo = true
           )
         )
         or
         (
           p.empleado_id is not null
           and exists (
             select 1
               from public.empleados e
               join public.membresias_usuario m
                 on m.user_id = p.user_id
                and m.activo = true
                and m.empresa_id = e.empresa_id
                and (
                  m.todos_locales = true
                  or (m.todos_locales = false and m.local_id = e.local_id)
                )
              where e.id = p.empleado_id
                and e.estado = 'activo'
           )
         )
       )
  );
$$;

-- Politicas vigentes en QA, byte a byte (estado ANTES de la migracion).
drop policy if exists qa_perfil_propio_select on public.perfiles;
create policy qa_perfil_propio_select on public.perfiles
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists qa_perfil_propio_update on public.perfiles;
create policy qa_perfil_propio_update on public.perfiles
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists qa_push_propio on public.suscripciones_push;
create policy qa_push_propio on public.suscripciones_push
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists membresia_propia_select on public.membresias_usuario;
create policy membresia_propia_select on public.membresias_usuario
  for select to authenticated
  using (
    (user_id = auth.uid())
    and (activo = true)
    and private.la_usuario_activo()
  );

grant usage on schema public to authenticated, anon;
grant select, insert, update, delete on public.perfiles, public.suscripciones_push, public.membresias_usuario to authenticated;
grant select on public.empleados to authenticated;
