-- PM26 P08 -- Defecto L (produccion): reproduccion del subconjunto
-- exacto de esquema de PRODUCCION (L&A Suite) necesario para validar,
-- en aislamiento, la migracion propuesta que anade aislamiento por
-- empresa/local a prefiltros_candidatos. Nunca contra QA ni
-- produccion. A diferencia de tests/pm26/p06h-f-aislado (que reproduce
-- QA), este archivo reproduce PRODUCCION -- el modelo de autorizacion
-- es distinto (private.la_tiene_local, no private.pm11_puede_*), y las
-- 3 politicas de partida son las reales de produccion, verificadas por
-- inspeccion de solo lectura el 2026-09-11.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated;
  end if;
end
$$;

create schema if not exists auth;
create table if not exists auth.users (id uuid primary key);

create or replace function auth.uid() returns uuid
language sql stable as $$
  select nullif(current_setting('app.current_uid', true), '')::uuid;
$$;

create schema if not exists private;

create table if not exists public.membresias_usuario (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  empresa_id text not null,
  local_id text,
  todos_locales boolean not null default false,
  rol text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.perfiles (
  user_id uuid primary key,
  rol text not null,
  empleado_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nombre text,
  activo boolean not null default true
);

create table if not exists public.prefiltro_limites (
  clave text primary key,
  ventana_inicio timestamptz not null,
  intentos integer not null,
  actualizado_en timestamptz not null
);

create table if not exists public.prefiltros_candidatos (
  token text primary key,
  creado_en timestamptz not null default now(),
  candidato_nombre text not null,
  estado text not null default 'pendiente',
  respuestas jsonb,
  resumen jsonb,
  completado_en timestamptz,
  expira_en timestamptz not null default (now() + interval '7 days')
);
alter table public.prefiltros_candidatos enable row level security;

-- Copias literales de los helpers ya vigentes en PRODUCCION (no se
-- modifican aqui -- verificados por inspeccion de solo lectura).
create or replace function private.la_usuario_activo() returns boolean
language sql stable security definer
set search_path to ''
as $$
  select (select auth.uid()) is not null
     and exists(
       select 1 from public.membresias_usuario m
        where m.user_id=(select auth.uid()) and m.activo=true
     )
     and not exists(
       select 1 from public.perfiles p
        where p.user_id=(select auth.uid()) and p.activo=false
     );
$$;

create or replace function private.la_tiene_empresa(p_empresa text) returns boolean
language sql stable security definer
set search_path to ''
as $$
  select private.la_usuario_activo()
     and nullif(btrim(p_empresa),'') is not null
     and exists(
       select 1 from public.membresias_usuario m
        where m.user_id=(select auth.uid()) and m.empresa_id=p_empresa and m.activo=true
     );
$$;

create or replace function private.la_tiene_local(p_empresa text, p_local text) returns boolean
language sql stable security definer
set search_path to ''
as $$
  select private.la_usuario_activo()
     and nullif(btrim(p_empresa),'') is not null
     and nullif(btrim(p_local),'') is not null
     and upper(btrim(p_local)) <> 'TODOS'
     and exists(
       select 1 from public.membresias_usuario m
        where m.user_id=(select auth.uid()) and m.empresa_id=p_empresa and m.activo=true
          and (m.todos_locales=true or m.local_id=p_local)
     );
$$;

-- Las 3 politicas REALES de produccion, texto exacto verificado por
-- inspeccion de solo lectura (incluye el patron optimizado
-- "(select auth.uid())" que produccion ya usa).
create policy "prefiltros - propietario lee"
  on public.prefiltros_candidatos for select to authenticated
  using (exists (select 1 from public.perfiles p where p.user_id = (select auth.uid()) and p.activo = true and p.rol = 'Propietario'::text));

create policy "prefiltros - propietario crea"
  on public.prefiltros_candidatos for insert to authenticated
  with check (exists (select 1 from public.perfiles p where p.user_id = (select auth.uid()) and p.activo = true and p.rol = 'Propietario'::text));

create policy "prefiltros - propietario borra"
  on public.prefiltros_candidatos for delete to authenticated
  using (exists (select 1 from public.perfiles p where p.user_id = (select auth.uid()) and p.activo = true and p.rol = 'Propietario'::text));

grant usage on schema public to authenticated, anon;
grant select, insert, delete on public.prefiltros_candidatos to authenticated;
-- Las 3 politicas reales de produccion consultan perfiles directamente
-- (no a traves de una funcion SECURITY DEFINER), asi que authenticated
-- necesita SELECT directo -- igual que en produccion real, donde el
-- flujo ya funciona hoy con estas mismas politicas.
grant select on public.perfiles, public.membresias_usuario to authenticated;
