-- PM26 P06h-F -- reproduccion del subconjunto exacto de esquema QA
-- necesario para validar, en aislamiento, la migracion propuesta del
-- aviso F (prefiltros_candidatos: aislamiento por empresa/local, RLS
-- en lectura, RPC en escritura). Nunca contra QA ni produccion.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role;
  end if;
end
$$;

-- QA real conserva grants directos por defecto para las funciones nuevas
-- de public. Reproducirlos aquí evita que un simple REVOKE ... FROM PUBLIC
-- dé una falsa sensación de aislamiento: anon/authenticated/service_role
-- deben existir como entradas ACL independientes antes de aplicar F.
alter default privileges in schema public
  grant execute on functions to anon, authenticated, service_role;

create schema if not exists auth;
create table if not exists auth.users (id uuid primary key);

create or replace function auth.uid() returns uuid
language sql stable as $$
  select nullif(current_setting('app.current_uid', true), '')::uuid;
$$;

create schema if not exists private;

-- Igual que en Supabase real: pgcrypto vive en el esquema "extensions".
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.membresias_usuario (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  empresa_id text not null,
  local_id text,
  todos_locales boolean not null default false,
  rol text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.empleados (
  id text primary key,
  empresa_id text not null,
  local_id text not null,
  estado text not null default 'activo'
);

create table if not exists public.perfiles (
  user_id uuid primary key,
  rol text not null default 'Básico',
  empleado_id text references public.empleados(id),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.almacen_kv (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  empresa_id text,
  local_id text
);

create table if not exists public.prefiltros_candidatos (
  token text primary key,
  creado_en timestamptz not null default now(),
  candidato_nombre text not null,
  estado text not null default 'pendiente',
  respuestas jsonb,
  resumen jsonb,
  completado_en timestamptz,
  expira_en timestamptz not null default (now() + interval '7 days')
);
alter table public.prefiltros_candidatos enable row level security;

-- Copias literales de los helpers ya vigentes en QA (no se modifican
-- aqui, solo se reproducen porque el diseno propuesto depende de
-- ellos).
create or replace function private.la_usuario_activo() returns boolean
language sql stable security definer
set search_path to 'public', 'auth', 'private', 'pg_temp'
as $$
  select exists (
    select 1
      from public.perfiles p
     where p.user_id = auth.uid()
       and p.activo = true
       and (
         (
           p.empleado_id is null
           and exists (
             select 1 from public.membresias_usuario m
              where m.user_id = p.user_id and m.activo = true
           )
         )
         or
         (
           p.empleado_id is not null
           and exists (
             select 1
               from public.empleados e
               join public.membresias_usuario m
                 on m.user_id = p.user_id
                and m.activo = true
                and m.empresa_id = e.empresa_id
                and (m.todos_locales = true or (m.todos_locales = false and m.local_id = e.local_id))
              where e.id = p.empleado_id and e.estado = 'activo'
           )
         )
       )
  );
$$;

create or replace function private.pm11_local_activo(p_empresa_id text, p_local_id text) returns boolean
language sql stable security definer
set search_path to 'public', 'auth', 'private', 'pg_temp'
as $$
  select
    nullif(btrim(p_empresa_id), '') is not null
    and nullif(btrim(p_local_id), '') is not null
    and upper(btrim(p_local_id)) not in ('TODOS', 'TODOS LOS LOCALES')
    and exists (
      select 1 from public.almacen_kv k
       where k.empresa_id = p_empresa_id and k.local_id = p_local_id
         and (
           (jsonb_typeof(k.value) = 'object' and k.value->>'id' = p_local_id
             and coalesce(nullif(k.value->>'empresaId',''), p_empresa_id) = p_empresa_id
             and lower(coalesce(k.value->>'activo','true')) in ('true','1','yes','si','sí'))
           or exists (
             select 1 from jsonb_array_elements(case when jsonb_typeof(k.value) = 'array' then k.value else '[]'::jsonb end) j
              where j->>'id' = p_local_id
                and coalesce(nullif(j->>'empresaId',''), p_empresa_id) = p_empresa_id
                and lower(coalesce(j->>'activo','true')) in ('true','1','yes','si','sí')
           )
         )
    );
$$;

create or replace function private.pm11_puede_ver_personal(p_empresa_id text, p_local_id text) returns boolean
language sql stable security definer
set search_path to 'public', 'auth', 'private', 'pg_temp'
as $$
  select private.la_usuario_activo()
     and nullif(btrim(p_empresa_id), '') is not null
     and nullif(btrim(p_local_id), '') is not null
     and upper(btrim(p_local_id)) not in ('TODOS', 'TODOS LOS LOCALES')
     and exists (
       select 1 from public.membresias_usuario m
        where m.user_id = auth.uid() and m.empresa_id = p_empresa_id and m.activo = true
          and ((m.rol = 'Propietario' and (m.todos_locales = true or m.local_id = p_local_id))
            or (m.rol = 'Encargado' and m.todos_locales = false and m.local_id = p_local_id))
     );
$$;

create or replace function private.pm11_puede_mutar_personal(p_empresa_id text, p_local_id text) returns boolean
language sql stable security definer
set search_path to 'public', 'auth', 'private', 'pg_temp'
as $$
  select private.la_usuario_activo()
     and private.pm11_local_activo(p_empresa_id, p_local_id)
     and exists (
       select 1 from public.membresias_usuario m
        where m.user_id = auth.uid() and m.empresa_id = p_empresa_id and m.activo = true
          and ((m.rol = 'Propietario' and (m.todos_locales = true or m.local_id = p_local_id))
            or (m.rol = 'Encargado' and m.todos_locales = false and m.local_id = p_local_id))
     );
$$;

grant usage on schema public to authenticated, anon;
grant select on public.empleados, public.membresias_usuario, public.perfiles to authenticated;
