-- PM12 · baseline productiva mínima candidata para habilitar P08.
-- NO es una migración QA ni contiene fixtures/datos.
-- Se valida primero en Supabase aislado antes de cualquier promoción remota.
-- Objetivo: crear solo la frontera de identidad/scope, ledger físico e idempotencia
-- que PM12-P08 necesita sobre una producción que conserva public.perfiles.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 1. Scope multiempresa/multilocal. Fail-closed: no se inventan membresías.
-- ---------------------------------------------------------------------------
create table public.membresias_usuario (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  empresa_id text not null,
  local_id text,
  todos_locales boolean not null default false,
  rol text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pm12_prod_membresia_empresa check (nullif(btrim(empresa_id),'') is not null),
  constraint pm12_prod_membresia_local check (
    (todos_locales = true and local_id is null)
    or
    (todos_locales = false and nullif(btrim(local_id),'') is not null)
  )
);
create unique index pm12_prod_membresia_scope
  on public.membresias_usuario(user_id,empresa_id,coalesce(local_id,'__TODOS__'));
alter table public.membresias_usuario enable row level security;
revoke all on table public.membresias_usuario from public, anon, authenticated;

create or replace function private.la_usuario_activo()
returns boolean
language sql
stable security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
     and exists(
       select 1
         from public.membresias_usuario m
        where m.user_id=(select auth.uid())
          and m.activo=true
     )
     and not exists(
       select 1
         from public.perfiles p
        where p.user_id=(select auth.uid())
          and p.activo=false
     );
$$;

create or replace function private.la_rol()
returns text
language sql
stable security definer
set search_path = ''
as $$
  select coalesce(
    (
      select p.rol
        from public.perfiles p
       where p.user_id=(select auth.uid()) and p.activo=true
       limit 1
    ),
    (
      select m.rol
        from public.membresias_usuario m
       where m.user_id=(select auth.uid()) and m.activo=true
       order by m.empresa_id,m.local_id nulls first
       limit 1
    )
  );
$$;

create or replace function private.la_tiene_empresa(p_empresa text)
returns boolean
language sql
stable security definer
set search_path = ''
as $$
  select private.la_usuario_activo()
     and nullif(btrim(p_empresa),'') is not null
     and exists(
       select 1
         from public.membresias_usuario m
        where m.user_id=(select auth.uid())
          and m.empresa_id=p_empresa
          and m.activo=true
     );
$$;

create or replace function private.la_tiene_local(p_empresa text,p_local text)
returns boolean
language sql
stable security definer
set search_path = ''
as $$
  select private.la_usuario_activo()
     and nullif(btrim(p_empresa),'') is not null
     and nullif(btrim(p_local),'') is not null
     and upper(btrim(p_local)) <> 'TODOS'
     and exists(
       select 1
         from public.membresias_usuario m
        where m.user_id=(select auth.uid())
          and m.empresa_id=p_empresa
          and m.activo=true
          and (m.todos_locales=true or m.local_id=p_local)
     );
$$;

revoke all on function private.la_usuario_activo() from public, anon, authenticated;
revoke all on function private.la_rol() from public, anon, authenticated;
revoke all on function private.la_tiene_empresa(text) from public, anon, authenticated;
revoke all on function private.la_tiene_local(text,text) from public, anon, authenticated;
-- RLS SELECT policies execute this helper as authenticated. P08 grants schema usage;
-- the helper itself must therefore be executable, while the underlying table stays hidden.
grant execute on function private.la_tiene_local(text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 2. Ledger físico mínimo heredando el contrato PM07, sin módulos de caja.
-- ---------------------------------------------------------------------------
create table public.stock_ubicacion (
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  almacen numeric(18,6) not null default 0 check (almacen >= 0),
  piso numeric(18,6) not null default 0 check (piso >= 0),
  minimo numeric(18,6) not null default 0 check (minimo >= 0),
  fraccionable boolean not null default false,
  precision_cantidad smallint not null default 0 check (precision_cantidad between 0 and 6),
  updated_at timestamptz not null default now(),
  local_operable boolean not null default true,
  primary key (empresa_id,local_id,producto_id)
);

create table public.stock_operaciones (
  operation_id text primary key,
  tipo text not null,
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  payload jsonb not null,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  ref_operation_id text,
  created_at timestamptz not null default now(),
  constraint stock_operaciones_tipo_check check (tipo in (
    'VENTA','REVERSO','TRASLADO_INTERNO','TRASLADO_ENTRE_LOCALES',
    'DEVOLUCION_CLIENTE','DEVOLUCION_PROVEEDOR'
  ))
);

create table public.movimientos_stock (
  id bigint generated by default as identity primary key,
  operation_id text not null references public.stock_operaciones(operation_id) on delete restrict,
  tipo text not null,
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  delta_almacen numeric(18,6) not null,
  delta_piso numeric(18,6) not null,
  delta_total numeric(18,6) not null,
  cantidad numeric(18,6) not null check (cantidad > 0),
  movimiento_original_id bigint references public.movimientos_stock(id) on delete restrict,
  datos jsonb not null default '{}'::jsonb,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint movimientos_stock_tipo_check check (tipo in (
    'VENTA','REVERSO','TRASLADO_INTERNO','TRASLADO_ENTRE_LOCALES',
    'DEVOLUCION_CLIENTE','DEVOLUCION_PROVEEDOR'
  )),
  constraint pm07_delta_total_consistente check (round(delta_total,6)=round(delta_almacen+delta_piso,6))
);

create index pm12_prod_mov_stock_scope
  on public.movimientos_stock(empresa_id,local_id,producto_id,created_at);
create unique index pm12_prod_un_reverso_por_movimiento
  on public.movimientos_stock(movimiento_original_id)
  where tipo='REVERSO' and movimiento_original_id is not null;

alter table public.stock_ubicacion enable row level security;
alter table public.stock_operaciones enable row level security;
alter table public.movimientos_stock enable row level security;

create policy pm12_prod_stock_select on public.stock_ubicacion
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));
create policy pm12_prod_operaciones_select on public.stock_operaciones
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));
create policy pm12_prod_movimientos_select on public.movimientos_stock
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));

revoke all on table public.stock_ubicacion from public, anon, authenticated;
revoke all on table public.stock_operaciones from public, anon, authenticated;
revoke all on table public.movimientos_stock from public, anon, authenticated;
grant select on table public.stock_ubicacion to authenticated;
grant select on table public.stock_operaciones to authenticated;
grant select on table public.movimientos_stock to authenticated;

create or replace function private.pm07_validar_cantidad(
  p_cantidad numeric,
  p_fraccionable boolean,
  p_precision smallint
) returns numeric
language plpgsql
immutable
set search_path = ''
as $$
declare v numeric;
begin
  if p_cantidad is null or p_cantidad::text in ('NaN','Infinity','-Infinity') then
    raise exception 'cantidad_invalida';
  end if;
  v := round(p_cantidad,greatest(0,least(6,coalesce(p_precision,0))));
  if v <= 0 then raise exception 'cantidad_invalida'; end if;
  if not coalesce(p_fraccionable,false) and v <> trunc(v) then raise exception 'unidad_indivisible'; end if;
  if p_cantidad <> v then raise exception 'precision_cantidad_excedida'; end if;
  return v;
end;
$$;

create or replace function private.pm07_puede_gestionar_stock()
returns boolean
language sql
stable security definer
set search_path = ''
as $$
  select private.la_usuario_activo()
     and coalesce(private.la_rol(),'') in ('Propietario','Encargado');
$$;

revoke all on function private.pm07_validar_cantidad(numeric,boolean,smallint) from public, anon, authenticated;
revoke all on function private.pm07_puede_gestionar_stock() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Bloqueo/idempotencia mínima PM08–PM09/G1, sin crear ledgers financieros.
-- ---------------------------------------------------------------------------
create or replace function private.pm08_validar_operation_id(p_operation_id text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare v text := btrim(coalesce(p_operation_id,''));
begin
  if v !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$' then raise exception 'operation_id_invalido'; end if;
  return v;
end;
$$;

create or replace function private.pm08_bloquear_operation_id(p_operation_id text)
returns void
language plpgsql
volatile
set search_path = ''
as $$
declare v text;
begin
  v := private.pm08_validar_operation_id(p_operation_id);
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('la-suite-pm08:'||v,0));
end;
$$;

create table private.g1_operation_ids_global (
  operation_id text primary key,
  ledger text not null,
  created_at timestamptz not null default now()
);
revoke all on table private.g1_operation_ids_global from public, anon, authenticated;

create or replace function private.g1_claim_operation_id()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare v_ledger text;
begin
  if new.operation_id is null or btrim(new.operation_id)='' then raise exception 'operation_id_requerido'; end if;
  insert into private.g1_operation_ids_global(operation_id,ledger)
  values(new.operation_id,tg_table_name)
  on conflict(operation_id) do nothing;
  select g.ledger into v_ledger
    from private.g1_operation_ids_global g
   where g.operation_id=new.operation_id;
  if v_ledger is distinct from tg_table_name then raise exception 'operation_id_conflict'; end if;
  return new;
end;
$$;

create trigger g1_operation_id_global
before insert on public.stock_operaciones
for each row execute function private.g1_claim_operation_id();

create or replace function private.pm09_bloquear_operation_id_stock(p_operation_id text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare v text; v_ledger text;
begin
  v := private.pm08_validar_operation_id(p_operation_id);
  perform private.pm08_bloquear_operation_id(v);
  select g.ledger into v_ledger
    from private.g1_operation_ids_global g
   where g.operation_id=v;
  if found and v_ledger <> 'stock_operaciones' then raise exception 'operation_id_conflict'; end if;
  return v;
end;
$$;

revoke all on function private.pm08_validar_operation_id(text) from public, anon, authenticated;
revoke all on function private.pm08_bloquear_operation_id(text) from public, anon, authenticated;
revoke all on function private.g1_claim_operation_id() from public, anon, authenticated;
revoke all on function private.pm09_bloquear_operation_id_stock(text) from public, anon, authenticated;

-- Sin INSERT de membresías, stock, movimientos ni operaciones.
-- Tras esta baseline, PM12-P08 se aplica como migración separada e inalterada.
