-- TEST-ONLY. Modelo mínimo de los objetos YA existentes en producción
-- que la baseline candidata debe respetar. No se despliega ni se copia a producción.
create table public.perfiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  rol text not null,
  empleado_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nombre text,
  activo boolean not null default true
);
alter table public.perfiles enable row level security;
revoke all on table public.perfiles from public, anon, authenticated;

-- Producción conserva además estas dos tablas operativas vacías. El fixture solo
-- reproduce su existencia para detectar colisiones de nombres; P08 no depende de ellas.
create table public.almacen_kv (
  key text primary key,
  value jsonb,
  empresa_id text,
  local_id text
);
alter table public.almacen_kv enable row level security;
revoke all on table public.almacen_kv from public, anon, authenticated;

create table public.movimientos_registro (
  id bigint generated by default as identity primary key,
  payload jsonb not null default '{}'::jsonb
);
alter table public.movimientos_registro enable row level security;
revoke all on table public.movimientos_registro from public, anon, authenticated;
