-- PM27 / C24 — baseline estructural pre-C13 para certificacion aislada PostgreSQL 17.
--
-- Este fixture NO contiene datos de negocio. Reproduce únicamente el contrato de
-- esquema, firmas y privilegios que las migraciones C13->C23 necesitan para
-- compilar y validar sus pre/postcondiciones. Las formas relevantes se contrastaron
-- por lectura contra L&A Suite QA (PostgreSQL 17) antes de versionarlo.
--
-- El estado deliberadamente representa un destino limpio PRE-C13:
--   * no contiene marcadores funcionales C13-C23;
--   * conserva el trigger global operation_id previo a C22;
--   * incluye private.es_propietario_activo() en estado todavía no endurecido,
--     para que C13-P5 demuestre el hardening real;
--   * mantiene RPC legacy ejecutables para verificar que C13 las retira.

\set ON_ERROR_STOP on

DO $roles$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END
$roles$;

CREATE SCHEMA auth;
CREATE SCHEMA private;
CREATE SCHEMA supabase_migrations;

CREATE TABLE auth.users (
  id uuid PRIMARY KEY
);

CREATE OR REPLACE FUNCTION auth.uid()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$ SELECT NULL::uuid $$;

CREATE TABLE public.empleados (
  id text PRIMARY KEY
);

CREATE TABLE public.perfiles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  rol text NOT NULL DEFAULT 'Básico',
  empleado_id text NULL REFERENCES public.empleados(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  nombre text NULL,
  activo boolean NOT NULL DEFAULT true,
  CONSTRAINT perfiles_rol_check CHECK (
    rol = ANY (ARRAY['Propietario'::text,'Encargado'::text,'Básico'::text,'Camarero/a'::text,'Cajero/a'::text,'Churrero/a'::text])
  ),
  CONSTRAINT pm11_perfiles_empleado_no_vacio CHECK (
    empleado_id IS NULL OR NULLIF(btrim(empleado_id), '') IS NOT NULL
  )
);

CREATE TABLE public.membresias_usuario (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  empresa_id text NOT NULL,
  local_id text NULL,
  todos_locales boolean NOT NULL DEFAULT false,
  rol text NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.almacen_kv (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  empresa_id text NULL,
  local_id text NULL
);

CREATE TABLE public.stock_ubicacion (
  empresa_id text NOT NULL,
  local_id text NOT NULL,
  producto_id text NOT NULL,
  almacen numeric NOT NULL DEFAULT 0 CHECK (almacen >= 0),
  piso numeric NOT NULL DEFAULT 0 CHECK (piso >= 0),
  minimo numeric NOT NULL DEFAULT 0 CHECK (minimo >= 0),
  fraccionable boolean NOT NULL DEFAULT false,
  precision_cantidad smallint NOT NULL DEFAULT 0 CHECK (precision_cantidad BETWEEN 0 AND 6),
  updated_at timestamptz NOT NULL DEFAULT now(),
  local_operable boolean NOT NULL DEFAULT true,
  unidad text NOT NULL DEFAULT 'ud',
  PRIMARY KEY (empresa_id, local_id, producto_id)
);

CREATE TABLE public.stock_operaciones (
  operation_id text PRIMARY KEY,
  tipo text NOT NULL,
  empresa_id text NOT NULL,
  local_id text NOT NULL,
  producto_id text NOT NULL,
  payload jsonb NOT NULL,
  actor_user_id uuid NOT NULL,
  ref_operation_id text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_operaciones_tipo_check CHECK (
    tipo = ANY (ARRAY['VENTA'::text,'REVERSO'::text,'TRASLADO_INTERNO'::text,'TRASLADO_ENTRE_LOCALES'::text,'DEVOLUCION_CLIENTE'::text,'DEVOLUCION_PROVEEDOR'::text])
    OR tipo = 'INVENTARIO_PM12'
  )
);

CREATE TABLE public.movimientos_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id text NOT NULL REFERENCES public.stock_operaciones(operation_id) ON DELETE RESTRICT,
  tipo text NOT NULL,
  empresa_id text NOT NULL,
  local_id text NOT NULL,
  producto_id text NOT NULL,
  delta_almacen numeric NOT NULL,
  delta_piso numeric NOT NULL,
  delta_total numeric NOT NULL,
  cantidad numeric NOT NULL CHECK (cantidad > 0),
  movimiento_original_id bigint NULL REFERENCES public.movimientos_stock(id) ON DELETE RESTRICT,
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT movimientos_stock_tipo_check CHECK (
    tipo = ANY (ARRAY['VENTA'::text,'REVERSO'::text,'TRASLADO_INTERNO'::text,'TRASLADO_ENTRE_LOCALES'::text,'DEVOLUCION_CLIENTE'::text,'DEVOLUCION_PROVEEDOR'::text])
    OR tipo = 'INVENTARIO_PM12'
  ),
  CONSTRAINT pm07_delta_total_consistente CHECK (round(delta_total, 6) = round(delta_almacen + delta_piso, 6))
);

CREATE TABLE public.clientes_empresa (
  id text PRIMARY KEY,
  empresa_id text NOT NULL,
  datos jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clientes_empresa_datos_empresa CHECK (
    (datos->>'empresaId') IS NULL OR (datos->>'empresaId') = empresa_id
  )
);

CREATE TABLE public.encargos_empresa (
  id text PRIMARY KEY,
  empresa_id text NOT NULL,
  local_id text NOT NULL,
  cliente_id text NULL,
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE private.g1_operation_ids_global (
  operation_id text PRIMARY KEY,
  ledger text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pagos_encargo (
  id text PRIMARY KEY,
  operation_id text NOT NULL UNIQUE,
  encargo_id text NOT NULL,
  empresa_id text NOT NULL,
  local_id text NOT NULL,
  concepto text NOT NULL CHECK (concepto = ANY (ARRAY['SEÑAL'::text,'RESTO_ENTREGA'::text,'OTRO'::text])),
  importe numeric NOT NULL CHECK (importe > 0),
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  estado text NOT NULL CHECK (estado = ANY (ARRAY['CONFIRMADO'::text,'REVERSO'::text])),
  revierte_pago_id text NULL REFERENCES public.pagos_encargo(id),
  medio_pago text NULL CHECK (medio_pago IS NULL OR medio_pago = ANY (ARRAY['Efectivo'::text,'Tarjeta'::text,'Transferencia'::text,'Otro'::text])),
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE supabase_migrations.schema_migrations (
  version text PRIMARY KEY,
  name text,
  created_by text
);

-- Helpers tenant / stock / caja preexistentes. Los cuerpos son stubs deliberados:
-- el paquete C24 valida firmas y sustituye las funciones que están en su alcance.
CREATE OR REPLACE FUNCTION private.la_usuario_activo()
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT true $$;

CREATE OR REPLACE FUNCTION private.la_tiene_empresa(p_empresa text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT p_empresa IS NOT NULL $$;

CREATE OR REPLACE FUNCTION private.la_tiene_local(p_empresa text, p_local text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT p_empresa IS NOT NULL AND p_local IS NOT NULL $$;

CREATE OR REPLACE FUNCTION private.es_propietario_activo()
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT true $$;

CREATE OR REPLACE FUNCTION private.la_rol()
RETURNS text LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','pg_temp'
AS $$ SELECT 'Propietario'::text $$;

CREATE OR REPLACE FUNCTION private.pm07_puede_vender()
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT true $$;

CREATE OR REPLACE FUNCTION private.pm07_puede_gestionar_stock()
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT true $$;

CREATE OR REPLACE FUNCTION private.pm07_validar_cantidad(
  p_cantidad numeric, p_fraccionable boolean, p_precision smallint
) RETURNS numeric
LANGUAGE sql
SET search_path='pg_catalog','pg_temp'
AS $$ SELECT p_cantidad $$;

CREATE OR REPLACE FUNCTION private.pm08_bloquear_operation_id(p_operation_id text)
RETURNS void LANGUAGE plpgsql
SET search_path='pg_catalog','pg_temp'
AS $$ BEGIN RETURN; END $$;

CREATE OR REPLACE FUNCTION private.pm09_bloquear_operation_id_stock(p_operation_id text)
RETURNS text LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT p_operation_id $$;

CREATE OR REPLACE FUNCTION private.pm08_puede_operar_caja()
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT true $$;

CREATE OR REPLACE FUNCTION private.pm08_local_operable(p_empresa_id text, p_local_id text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT p_empresa_id IS NOT NULL AND p_local_id IS NOT NULL $$;

CREATE OR REPLACE FUNCTION private.pm08_validar_dinero(
  p_importe numeric, p_permite_cero boolean, p_permite_negativo boolean
) RETURNS numeric
LANGUAGE sql
SET search_path='pg_catalog','pg_temp'
AS $$ SELECT p_importe $$;

CREATE OR REPLACE FUNCTION private.pm12_confirmar_ajuste_stock(
  p_operation_id text, p_empresa_id text, p_local_id text,
  p_intencion jsonb, p_plan jsonb, p_bases jsonb
) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION private.pm12_cancelar_conteo_stock(
  p_empresa_id text, p_local_id text, p_conteo jsonb, p_cancelacion jsonb
) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION private.g1_claim_operation_id()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ BEGIN RETURN NEW; END $$;

CREATE TRIGGER g1_operation_id_global
BEFORE INSERT ON public.pagos_encargo
FOR EACH ROW EXECUTE FUNCTION private.g1_claim_operation_id();

-- RPC públicas pre-C13/C18/C19/C21/C23: firmas reales, cuerpos sin marcadores.
CREATE OR REPLACE FUNCTION public.obtener_contexto_operativo()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.registrar_venta_stock(
  p_operation_id text, p_empresa_id text, p_local_id text, p_producto_id text,
  p_cantidad numeric, p_datos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.registrar_venta_stock_carrito(
  p_operation_id text, p_empresa_id text, p_local_id text,
  p_lineas jsonb, p_datos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.trasladar_stock_interno(
  p_operation_id text, p_empresa_id text, p_local_id text, p_producto_id text,
  p_origen text, p_destino text, p_cantidad numeric, p_datos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.trasladar_stock_entre_locales(
  p_operation_id text, p_empresa_id text, p_origen_local_id text, p_destino_local_id text,
  p_producto_origen_id text, p_producto_destino_id text, p_cantidad numeric,
  p_datos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.registrar_encargo(
  p_id text, p_empresa_id text, p_local_id text, p_cliente_id text,
  p_total numeric, p_estado text DEFAULT 'Pendiente', p_datos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.registrar_pago_encargo(
  p_id text, p_operation_id text, p_encargo_id text, p_empresa_id text,
  p_local_id text, p_concepto text, p_importe numeric, p_fecha date,
  p_medio_pago text, p_datos jsonb
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.revertir_pago_encargo(
  p_id text, p_operation_id text, p_pago_id text, p_motivo text
) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

-- RPC legacy todavía expuestas: C13 debe retirar EXECUTE a authenticated.
CREATE OR REPLACE FUNCTION public.descontar_stock_carrito(p_lineas jsonb, p_local_id text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

CREATE OR REPLACE FUNCTION public.anular_venta_tpv(p_venta_id text, p_motivo text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path='public','auth','private','pg_temp'
AS $$ SELECT '{}'::jsonb $$;

-- Superficie pre-hardening deliberadamente amplia para comprobar REVOKE reales.
GRANT USAGE ON SCHEMA public, auth, private TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
  ON public.encargos_empresa, public.pagos_encargo TO authenticated;

REVOKE ALL ON FUNCTION public.registrar_pago_encargo(text,text,text,text,text,text,numeric,date,text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.revertir_pago_encargo(text,text,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_pago_encargo(text,text,text,text,text,text,numeric,date,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revertir_pago_encargo(text,text,text,text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.descontar_stock_carrito(jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.anular_venta_tpv(text,text) TO authenticated;

-- El helper se deja con EXECUTE heredado de PUBLIC y search_path mutable:
-- precisamente el estado que C13-P5 debe endurecer.
GRANT EXECUTE ON FUNCTION private.es_propietario_activo() TO authenticated;

SELECT 'PM27_C24_BASELINE_PRE_C13=PASS' AS resultado;
