-- ABC F4 B07 / subpunto 3 — deduplicación, validación y aplicación controlada.
--
-- El evento se conserva antes de intentar el efecto. La única transición de
-- pago se delega en abc_resolver_intento, que ya protege reservas, pagos,
-- checkout y trazabilidad de la operación del sistema.

begin;
set local lock_timeout='5s';
set local statement_timeout='30s';

do $$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regprocedure('public.abc_b07_obtener_configuracion(text,text)') is null then
    v_missing := array_append(v_missing, 'abc_b07_obtener_configuracion');
  end if;
  if to_regprocedure('public.abc_resolver_intento(text,text,text,uuid,text,text,text,numeric,numeric,numeric,jsonb)') is null then
    v_missing := array_append(v_missing, 'abc_resolver_intento');
  end if;
  if to_regprocedure('private.abc_request_hash(jsonb)') is null then
    v_missing := array_append(v_missing, 'abc_request_hash');
  end if;
  if cardinality(v_missing) > 0 then
    raise exception 'ABC_F4_B07_PROCESS_PREFLIGHT_FALLO:%', array_to_string(v_missing, ',');
  end if;
  if to_regclass('public.abc_b07_eventos_proveedor') is not null
     or to_regprocedure('public.abc_b07_procesar_evento(text,text,text,text,text,text,numeric,text,timestamptz,jsonb)') is not null then
    raise exception 'ABC_F4_B07_PROCESS_PREFLIGHT_FALLO: objetos de procesamiento ya existen';
  end if;
end $$;

create table public.abc_b07_eventos_proveedor (
  id bigint generated by default as identity primary key,
  provider_code text not null,
  provider_account_id text not null,
  provider_event_id text not null,
  event_fingerprint text not null,
  provider_reference text not null,
  event_type text not null,
  status text not null,
  amount numeric(24,8) not null check (amount > 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  occurred_at timestamptz,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  empresa_id text not null,
  local_id text not null,
  intento_id uuid,
  operation_id text not null,
  processing_status text not null default 'RECIBIDO'
    check (processing_status in ('RECIBIDO','APLICADO','RECHAZADO','IGNORADO')),
  result jsonb,
  error_code text,
  conflict_count integer not null default 0 check (conflict_count >= 0),
  last_conflict_fingerprint text,
  last_conflict_payload jsonb,
  last_conflict_at timestamptz,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  constraint abc_b07_event_provider_ck check (provider_code ~ '^[A-Z][A-Z0-9_]{1,63}$'),
  constraint abc_b07_event_account_ck check (char_length(btrim(provider_account_id)) between 1 and 240),
  constraint abc_b07_event_id_ck check (char_length(btrim(provider_event_id)) between 1 and 512),
  constraint abc_b07_event_fingerprint_ck check (event_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint abc_b07_event_reference_ck check (char_length(btrim(provider_reference)) between 1 and 240),
  constraint abc_b07_event_type_ck check (char_length(btrim(event_type)) between 1 and 96),
  constraint abc_b07_event_status_ck check (char_length(btrim(status)) between 1 and 96),
  constraint abc_b07_event_operation_ck check (operation_id ~ '^abc\.b07\.[A-Za-z0-9]{64}$'),
  constraint abc_b07_event_payload_conflict_ck check (
    last_conflict_payload is null or jsonb_typeof(last_conflict_payload) = 'object'
  ),
  constraint abc_b07_event_processing_ck check (
    (processing_status = 'RECIBIDO' and processed_at is null)
    or (processing_status <> 'RECIBIDO' and processed_at is not null)
  ),
  constraint abc_b07_event_scope_fk
    foreign key (empresa_id, local_id)
    references public.locales(empresa_id, id) on delete restrict
);

create unique index abc_b07_event_key_uq
  on public.abc_b07_eventos_proveedor(provider_code, provider_account_id, provider_event_id);
create unique index abc_b07_event_operation_uq
  on public.abc_b07_eventos_proveedor(empresa_id, local_id, operation_id);
create index abc_b07_event_attempt_idx
  on public.abc_b07_eventos_proveedor(empresa_id, local_id, intento_id, created_at desc);

alter table public.abc_b07_eventos_proveedor enable row level security;
revoke all on table public.abc_b07_eventos_proveedor from public, anon, authenticated, service_role;

comment on table public.abc_b07_eventos_proveedor is
  'B07: evidencia de eventos del proveedor, deduplicada por cuenta comercial y evento.';
comment on column public.abc_b07_eventos_proveedor.last_conflict_payload is
  'Último payload con la misma clave de proveedor pero contenido distinto; nunca contiene datos de tarjeta.';

create function private.abc_b07_payload_sin_tarjeta(p_payload jsonb)
returns boolean
language plpgsql
immutable
security definer
set search_path=''
as $$
declare
  v_item record;
  v_key text;
begin
  if p_payload is null then return false; end if;
  if jsonb_typeof(p_payload) = 'object' then
    for v_item in select key, value from jsonb_each(p_payload) loop
      v_key := lower(replace(replace(v_item.key, '-', '_'), ' ', '_'));
      if v_key in (
        'pan','cvv','cvc','cid','card_number','cardnumber','numero_tarjeta',
        'security_code','payment_method_details','private_key','secret_value'
      ) then
        return false;
      end if;
      if jsonb_typeof(v_item.value) in ('object','array')
         and not private.abc_b07_payload_sin_tarjeta(v_item.value) then
        return false;
      end if;
    end loop;
  elsif jsonb_typeof(p_payload) = 'array' then
    for v_item in select value from jsonb_array_elements(p_payload) loop
      if jsonb_typeof(v_item.value) in ('object','array')
         and not private.abc_b07_payload_sin_tarjeta(v_item.value) then
        return false;
      end if;
    end loop;
  end if;
  return true;
end;
$$;

create function public.abc_b07_procesar_evento(
  p_provider_code text,
  p_provider_account_id text,
  p_provider_event_id text,
  p_provider_reference text,
  p_event_type text,
  p_status text,
  p_amount numeric,
  p_currency text,
  p_occurred_at timestamptz,
  p_payload jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $$
declare
  v_provider_code text := upper(btrim(coalesce(p_provider_code, '')));
  v_account_id text := btrim(coalesce(p_provider_account_id, ''));
  v_event_id text := btrim(coalesce(p_provider_event_id, ''));
  v_reference text := btrim(coalesce(p_provider_reference, ''));
  v_event_type text := upper(btrim(coalesce(p_event_type, '')));
  v_status text := upper(btrim(coalesce(p_status, '')));
  v_currency text := upper(btrim(coalesce(p_currency, '')));
  v_config jsonb;
  v_empresa_id text;
  v_local_id text;
  v_fingerprint text;
  v_operation_id text;
  v_intento public.pago_intentos%rowtype;
  v_event public.abc_b07_eventos_proveedor%rowtype;
  v_result jsonb;
  v_estado text;
  v_sqlstate text;
begin
  if v_provider_code = '' or v_account_id = '' or v_event_id = '' or v_reference = ''
     or v_event_type = '' or v_status = '' then
    raise exception 'abc_b07_evento_requerido';
  end if;
  if p_amount is null or p_amount <= 0 then raise exception 'abc_b07_importe_invalido'; end if;
  if v_currency !~ '^[A-Z]{3}$' then raise exception 'abc_b07_moneda_invalida'; end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object'
     or not private.abc_b07_payload_sin_tarjeta(p_payload) then
    raise exception 'abc_b07_payload_invalido';
  end if;

  v_config := public.abc_b07_obtener_configuracion(v_provider_code, v_account_id);
  if v_config = '{}'::jsonb then raise exception 'abc_b07_configuracion_no_encontrada'; end if;
  v_empresa_id := nullif(btrim(v_config->>'empresa_id'), '');
  v_local_id := nullif(btrim(v_config->>'local_id'), '');
  if v_empresa_id is null or v_local_id is null then
    raise exception 'abc_b07_ambito_servidor_invalido';
  end if;

  v_fingerprint := private.abc_request_hash(jsonb_build_object(
    'provider_code', v_provider_code,
    'provider_account_id', v_account_id,
    'provider_event_id', v_event_id,
    'provider_reference', v_reference,
    'event_type', v_event_type,
    'status', v_status,
    'amount', p_amount,
    'currency', v_currency,
    'occurred_at', p_occurred_at,
    'payload', p_payload
  ));
  v_operation_id := 'abc.b07.' || private.abc_request_hash(jsonb_build_object(
    'provider_code', v_provider_code,
    'provider_account_id', v_account_id,
    'provider_event_id', v_event_id
  ));

  insert into public.abc_b07_eventos_proveedor(
    provider_code,provider_account_id,provider_event_id,event_fingerprint,
    provider_reference,event_type,status,amount,currency,occurred_at,payload,
    empresa_id,local_id,operation_id
  ) values (
    v_provider_code,v_account_id,v_event_id,v_fingerprint,
    v_reference,v_event_type,v_status,p_amount,v_currency,p_occurred_at,p_payload,
    v_empresa_id,v_local_id,v_operation_id
  ) on conflict (provider_code,provider_account_id,provider_event_id) do nothing;

  select * into v_event
    from public.abc_b07_eventos_proveedor
   where provider_code=v_provider_code
     and provider_account_id=v_account_id
     and provider_event_id=v_event_id
   for update;
  if v_event.event_fingerprint <> v_fingerprint then
    update public.abc_b07_eventos_proveedor
       set conflict_count=conflict_count+1,
           last_conflict_fingerprint=v_fingerprint,
           last_conflict_payload=p_payload,
           last_conflict_at=now()
     where id=v_event.id;
    return jsonb_build_object(
      'ok',false,'conflict',true,'effect_applied',false,
      'error','provider_event_key_conflict','provider_event_id',v_event_id
    );
  end if;
  if v_event.processing_status <> 'RECIBIDO' then
    return coalesce(v_event.result, jsonb_build_object(
      'ok',true,'effect_applied',false,'provider_event_id',v_event_id
    )) || jsonb_build_object('replayed',true);
  end if;

  select i.* into v_intento
    from public.pago_intentos i
   where i.empresa_id=v_empresa_id
     and i.local_id=v_local_id
     and (i.provider_code is null or i.provider_code=v_provider_code)
     and i.provider_reference=v_reference
   order by i.started_at desc, i.id desc
   limit 1
   for update;
  if not found then
    v_result := jsonb_build_object(
      'ok',false,'effect_applied',false,'error','payment_attempt_not_linked',
      'provider_event_id',v_event_id
    );
    update public.abc_b07_eventos_proveedor
       set processing_status='RECHAZADO',result=v_result,error_code='PAYMENT_ATTEMPT_NOT_LINKED',processed_at=now()
     where id=v_event.id;
    return v_result;
  end if;

  if v_intento.payment_currency_code <> v_currency
     or v_intento.requested_amount <> p_amount then
    v_result := jsonb_build_object(
      'ok',false,'effect_applied',false,'error','payment_amount_or_currency_mismatch',
      'provider_event_id',v_event_id,'intento_id',v_intento.id
    );
    update public.abc_b07_eventos_proveedor
       set intento_id=v_intento.id,processing_status='RECHAZADO',result=v_result,
           error_code='PAYMENT_AMOUNT_OR_CURRENCY_MISMATCH',processed_at=now()
     where id=v_event.id;
    return v_result;
  end if;

  v_estado := case v_status
    when 'CONFIRMADO' then 'CONFIRMADO'
    when 'CAPTURED' then 'CONFIRMADO'
    when 'PAID' then 'CONFIRMADO'
    when 'SETTLED' then 'CONFIRMADO'
    when 'AUTORIZADO' then 'AUTORIZADO'
    when 'AUTHORIZED' then 'AUTORIZADO'
    when 'RECHAZADO' then 'RECHAZADO'
    when 'FAILED' then 'RECHAZADO'
    when 'DECLINED' then 'RECHAZADO'
    when 'CANCELADO' then 'CANCELADO'
    when 'CANCELLED' then 'CANCELADO'
    when 'VOIDED' then 'CANCELADO'
    else null
  end;
  if v_estado is null then
    v_result := jsonb_build_object(
      'ok',true,'effect_applied',false,'ignored',true,
      'error','provider_status_not_terminal','provider_event_id',v_event_id,
      'intento_id',v_intento.id
    );
    update public.abc_b07_eventos_proveedor
       set intento_id=v_intento.id,processing_status='IGNORADO',result=v_result,processed_at=now()
     where id=v_event.id;
    return v_result;
  end if;

  begin
    v_result := public.abc_resolver_intento(
      v_operation_id,v_empresa_id,v_local_id,v_intento.id,v_estado,
      v_provider_code,v_reference,
      case when v_estado in ('AUTORIZADO','CONFIRMADO') then p_amount else null end,
      case when v_estado='CONFIRMADO' then p_amount else null end,
      case when v_estado='CONFIRMADO' then p_amount else null end,
      jsonb_build_object('provider_event_id',v_event_id,'event_type',v_event_type,'payload',p_payload)
    );
  exception when others then
    get stacked diagnostics v_sqlstate = returned_sqlstate;
    v_result := jsonb_build_object(
      'ok',false,'effect_applied',false,'error','payment_transition_rejected',
      'provider_event_id',v_event_id,'intento_id',v_intento.id
    );
    update public.abc_b07_eventos_proveedor
       set intento_id=v_intento.id,processing_status='RECHAZADO',result=v_result,
           error_code='PAYMENT_TRANSITION_REJECTED_' || coalesce(v_sqlstate,'UNKNOWN'),processed_at=now()
     where id=v_event.id;
    return v_result;
  end;

  v_result := coalesce(v_result,'{}'::jsonb) || jsonb_build_object(
    'ok',true,'effect_applied',true,'provider_event_id',v_event_id,
    'intento_id',v_intento.id
  );
  update public.abc_b07_eventos_proveedor
     set intento_id=v_intento.id,processing_status='APLICADO',result=v_result,processed_at=now()
   where id=v_event.id;
  return v_result;
end;
$$;

comment on function public.abc_b07_procesar_evento(text,text,text,text,text,text,numeric,text,timestamptz,jsonb) is
  'B07: deduplica y valida un evento de proveedor; la transición económica delega en abc_resolver_intento.';

revoke all on function private.abc_b07_payload_sin_tarjeta(jsonb)
  from public, anon, authenticated, service_role;
revoke all on function public.abc_b07_procesar_evento(text,text,text,text,text,text,numeric,text,timestamptz,jsonb)
  from public, anon, authenticated, service_role;
grant execute on function public.abc_b07_procesar_evento(text,text,text,text,text,text,numeric,text,timestamptz,jsonb)
  to service_role;

commit;
