-- ABC F2 M01 — base transaccional y caja.
-- Aditiva, compatible con clientes legacy y sin activar ningún flujo ABC.
-- No modifica RPC existentes, stock ni arqueos_caja legacy.

do $$
begin
  if to_regclass('public.empresas') is null
     or to_regclass('public.locales') is null
     or to_regclass('public.caja_operaciones') is null
     or to_regclass('private.g1_operation_ids_global') is null
     or to_regprocedure('private.g1_claim_operation_id()') is null
     or to_regprocedure('private.la_tiene_local(text,text)') is null then
    raise exception 'ABC_F2_M01_PREFLIGHT_FALLO: dependencias base ausentes';
  end if;

  if to_regclass('public.terminales_tpv') is not null
     or to_regclass('public.abc_operaciones') is not null
     or to_regclass('public.abc_eventos') is not null
     or to_regclass('public.cajas_fisicas') is not null
     or to_regclass('public.caja_sesiones') is not null
     or to_regclass('public.caja_sesion_terminales') is not null
     or to_regclass('public.caja_cierres') is not null
     or to_regclass('public.caja_conteos') is not null
     or to_regclass('public.efectos_pendientes') is not null then
    raise exception 'ABC_F2_M01_PREFLIGHT_FALLO: objetos M01 ya existen';
  end if;
end $$;

create unique index if not exists abc_locales_empresa_id_id_uq
  on public.locales(empresa_id,id);

create table public.terminales_tpv (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  nombre text not null,
  device_key text,
  activo boolean not null default true,
  capacidades jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  constraint abc_terminal_nombre check (nullif(btrim(nombre),'') is not null),
  constraint abc_terminal_device_key check (device_key is null or nullif(btrim(device_key),'') is not null),
  constraint abc_terminal_local_fk
    foreign key (empresa_id,local_id)
    references public.locales(empresa_id,id) on delete restrict
);
create unique index abc_terminal_scope_id_uq on public.terminales_tpv(empresa_id,local_id,id);
create unique index abc_terminal_device_key_uq
  on public.terminales_tpv(empresa_id,local_id,device_key)
  where device_key is not null;
create index abc_terminal_scope_idx on public.terminales_tpv(empresa_id,local_id,activo);

create table public.abc_operaciones (
  operation_id text primary key,
  empresa_id text not null,
  local_id text not null,
  command_type text not null,
  request_hash text not null,
  status text not null default 'PROCESANDO',
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  terminal_id uuid,
  request jsonb not null default '{}'::jsonb,
  resultado jsonb,
  error jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint abc_operacion_id_formato
    check (operation_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'),
  constraint abc_operacion_command_type
    check (nullif(btrim(command_type),'') is not null),
  constraint abc_operacion_request_hash
    check (request_hash ~ '^[0-9a-f]{64}$'),
  constraint abc_operacion_status
    check (status in ('PROCESANDO','COMPLETADA','FALLIDA')),
  constraint abc_operacion_estado_consistente check (
    (status='PROCESANDO' and completed_at is null and resultado is null and error is null)
    or
    (status='COMPLETADA' and completed_at is not null and resultado is not null and error is null)
    or
    (status='FALLIDA' and completed_at is not null and error is not null)
  ),
  constraint abc_operacion_local_fk
    foreign key (empresa_id,local_id)
    references public.locales(empresa_id,id) on delete restrict,
  constraint abc_operacion_terminal_fk
    foreign key (empresa_id,local_id,terminal_id)
    references public.terminales_tpv(empresa_id,local_id,id) on delete restrict
);
create unique index abc_operacion_scope_id_uq
  on public.abc_operaciones(empresa_id,local_id,operation_id);
create index abc_operacion_scope_created_idx
  on public.abc_operaciones(empresa_id,local_id,created_at desc);

create trigger g1_operation_id_global
before insert on public.abc_operaciones
for each row execute function private.g1_claim_operation_id();

create table public.abc_eventos (
  id bigint generated by default as identity primary key,
  empresa_id text not null,
  local_id text not null,
  operation_id text not null,
  aggregate_type text not null,
  aggregate_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  terminal_id uuid,
  occurred_at timestamptz not null,
  operating_day date not null,
  created_at timestamptz not null default now(),
  constraint abc_evento_aggregate_type check (nullif(btrim(aggregate_type),'') is not null),
  constraint abc_evento_aggregate_id check (nullif(btrim(aggregate_id),'') is not null),
  constraint abc_evento_event_type check (nullif(btrim(event_type),'') is not null),
  constraint abc_evento_operacion_fk
    foreign key (empresa_id,local_id,operation_id)
    references public.abc_operaciones(empresa_id,local_id,operation_id) on delete restrict,
  constraint abc_evento_terminal_fk
    foreign key (empresa_id,local_id,terminal_id)
    references public.terminales_tpv(empresa_id,local_id,id) on delete restrict
);
create index abc_evento_aggregate_idx
  on public.abc_eventos(empresa_id,local_id,aggregate_type,aggregate_id,id);
create index abc_evento_operacion_idx
  on public.abc_eventos(operation_id,id);

create table public.cajas_fisicas (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint abc_caja_nombre check (nullif(btrim(nombre),'') is not null),
  constraint abc_caja_local_fk
    foreign key (empresa_id,local_id)
    references public.locales(empresa_id,id) on delete restrict
);
create unique index abc_caja_scope_id_uq on public.cajas_fisicas(empresa_id,local_id,id);
create index abc_caja_scope_idx on public.cajas_fisicas(empresa_id,local_id,activo);

create table public.caja_sesiones (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  caja_id uuid not null,
  estado text not null default 'PREPARANDO_APERTURA',
  version bigint not null default 1,
  abierta_at timestamptz,
  cerrada_at timestamptz,
  abierta_por uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint abc_sesion_estado
    check (estado in (
      'PREPARANDO_APERTURA','ABIERTA','EN_CIERRE',
      'CIERRE_PROVISIONAL','CERRADA_FINAL','APERTURA_CANCELADA'
    )),
  constraint abc_sesion_version check (version >= 1),
  constraint abc_sesion_tiempos check (
    (estado in ('CERRADA_FINAL','APERTURA_CANCELADA') and cerrada_at is not null)
    or
    (estado not in ('CERRADA_FINAL','APERTURA_CANCELADA') and cerrada_at is null)
  ),
  constraint abc_sesion_caja_fk
    foreign key (empresa_id,local_id,caja_id)
    references public.cajas_fisicas(empresa_id,local_id,id) on delete restrict
);
create unique index abc_sesion_scope_id_uq
  on public.caja_sesiones(empresa_id,local_id,id);
create unique index abc_sesion_activa_por_caja_uq
  on public.caja_sesiones(caja_id)
  where estado in ('PREPARANDO_APERTURA','ABIERTA','EN_CIERRE','CIERRE_PROVISIONAL');
create index abc_sesion_scope_estado_idx
  on public.caja_sesiones(empresa_id,local_id,estado,created_at desc);

create table public.caja_sesion_terminales (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  session_id uuid not null,
  terminal_id uuid not null,
  desde timestamptz not null default now(),
  hasta timestamptz,
  created_at timestamptz not null default now(),
  constraint abc_sesion_terminal_rango check (hasta is null or hasta > desde),
  constraint abc_sesion_terminal_sesion_fk
    foreign key (empresa_id,local_id,session_id)
    references public.caja_sesiones(empresa_id,local_id,id) on delete restrict,
  constraint abc_sesion_terminal_terminal_fk
    foreign key (empresa_id,local_id,terminal_id)
    references public.terminales_tpv(empresa_id,local_id,id) on delete restrict
);
create unique index abc_sesion_terminal_activo_uq
  on public.caja_sesion_terminales(session_id,terminal_id)
  where hasta is null;
create index abc_sesion_terminal_scope_idx
  on public.caja_sesion_terminales(empresa_id,local_id,session_id,desde);

create table public.caja_cierres (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  session_id uuid not null,
  estado text not null default 'INICIADO',
  version bigint not null default 1,
  expected_snapshot jsonb not null default '{}'::jsonb,
  iniciado_por uuid not null references auth.users(id) on delete restrict,
  finalizado_por uuid references auth.users(id) on delete restrict,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint abc_cierre_estado check (estado in ('INICIADO','PROVISIONAL','FINAL','CANCELADO')),
  constraint abc_cierre_version check (version >= 1),
  constraint abc_cierre_tiempos check (
    (estado in ('FINAL','CANCELADO') and completed_at is not null)
    or
    (estado in ('INICIADO','PROVISIONAL') and completed_at is null)
  ),
  constraint abc_cierre_finalizador check (
    (estado in ('FINAL','CANCELADO') and finalizado_por is not null)
    or
    (estado in ('INICIADO','PROVISIONAL') and finalizado_por is null)
  ),
  constraint abc_cierre_sesion_fk
    foreign key (empresa_id,local_id,session_id)
    references public.caja_sesiones(empresa_id,local_id,id) on delete restrict
);
create unique index abc_cierre_scope_id_uq
  on public.caja_cierres(empresa_id,local_id,id);
create unique index abc_cierre_activo_por_sesion_uq
  on public.caja_cierres(session_id)
  where estado in ('INICIADO','PROVISIONAL');
create unique index abc_cierre_final_por_sesion_uq
  on public.caja_cierres(session_id)
  where estado='FINAL';

create table public.caja_conteos (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  cierre_id uuid not null,
  currency_code text not null,
  numero integer not null,
  counted_amount numeric(24,8) not null,
  denominaciones jsonb not null default '{}'::jsonb,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint abc_conteo_moneda check (currency_code ~ '^[A-Z]{3}$'),
  constraint abc_conteo_numero check (numero > 0),
  constraint abc_conteo_importe check (counted_amount >= 0),
  constraint abc_conteo_cierre_fk
    foreign key (empresa_id,local_id,cierre_id)
    references public.caja_cierres(empresa_id,local_id,id) on delete restrict,
  constraint abc_conteo_numero_uq unique (cierre_id,currency_code,numero)
);
create index abc_conteo_scope_idx
  on public.caja_conteos(empresa_id,local_id,cierre_id,currency_code,numero);

create table public.efectos_pendientes (
  id uuid primary key default gen_random_uuid(),
  empresa_id text not null,
  local_id text not null,
  abc_command_id text not null,
  tipo text not null,
  dedupe_key text not null,
  payload jsonb not null default '{}'::jsonb,
  estado text not null default 'PENDIENTE',
  attempt_count integer not null default 0,
  next_attempt_at timestamptz,
  last_error jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint abc_efecto_tipo check (nullif(btrim(tipo),'') is not null),
  constraint abc_efecto_dedupe check (nullif(btrim(dedupe_key),'') is not null),
  constraint abc_efecto_estado
    check (estado in ('PENDIENTE','EN_PROCESO','COMPLETADO','ERROR','ABANDONADO')),
  constraint abc_efecto_attempt_count check (attempt_count >= 0),
  constraint abc_efecto_completed check (
    (estado='COMPLETADO' and completed_at is not null)
    or
    (estado<>'COMPLETADO')
  ),
  constraint abc_efecto_operacion_fk
    foreign key (empresa_id,local_id,abc_command_id)
    references public.abc_operaciones(empresa_id,local_id,operation_id) on delete restrict,
  constraint abc_efecto_dedupe_uq unique (empresa_id,dedupe_key)
);
create index abc_efecto_pendiente_idx
  on public.efectos_pendientes(estado,next_attempt_at,created_at)
  where estado in ('PENDIENTE','ERROR');

alter table public.caja_operaciones
  add column abc_command_id text,
  add column caja_id uuid,
  add column session_id uuid,
  add column terminal_id uuid,
  add column currency_code text,
  add column operating_day date,
  add column occurred_at timestamptz,
  add column categoria text;

alter table public.caja_operaciones
  add constraint abc_caja_operacion_moneda
    check (currency_code is null or currency_code ~ '^[A-Z]{3}$'),
  add constraint abc_caja_operacion_categoria
    check (categoria is null or nullif(btrim(categoria),'') is not null),
  add constraint abc_caja_operacion_contexto_completo
    check (
      abc_command_id is null
      or (
        caja_id is not null
        and session_id is not null
        and terminal_id is not null
        and currency_code is not null
        and operating_day is not null
        and occurred_at is not null
        and categoria is not null
      )
    ),
  add constraint abc_caja_operacion_command_fk
    foreign key (empresa_id,local_id,abc_command_id)
    references public.abc_operaciones(empresa_id,local_id,operation_id) on delete restrict,
  add constraint abc_caja_operacion_caja_fk
    foreign key (empresa_id,local_id,caja_id)
    references public.cajas_fisicas(empresa_id,local_id,id) on delete restrict,
  add constraint abc_caja_operacion_sesion_fk
    foreign key (empresa_id,local_id,session_id)
    references public.caja_sesiones(empresa_id,local_id,id) on delete restrict,
  add constraint abc_caja_operacion_terminal_fk
    foreign key (empresa_id,local_id,terminal_id)
    references public.terminales_tpv(empresa_id,local_id,id) on delete restrict;

create index abc_caja_operacion_session_idx
  on public.caja_operaciones(empresa_id,local_id,session_id,occurred_at)
  where session_id is not null;
create index abc_caja_operacion_command_idx
  on public.caja_operaciones(abc_command_id)
  where abc_command_id is not null;

alter table public.terminales_tpv enable row level security;
alter table public.abc_operaciones enable row level security;
alter table public.abc_eventos enable row level security;
alter table public.cajas_fisicas enable row level security;
alter table public.caja_sesiones enable row level security;
alter table public.caja_sesion_terminales enable row level security;
alter table public.caja_cierres enable row level security;
alter table public.caja_conteos enable row level security;
alter table public.efectos_pendientes enable row level security;

create policy abc_terminal_select on public.terminales_tpv
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_operacion_select on public.abc_operaciones
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_evento_select on public.abc_eventos
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_caja_fisica_select on public.cajas_fisicas
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_caja_sesion_select on public.caja_sesiones
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_caja_sesion_terminal_select on public.caja_sesion_terminales
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_caja_cierre_select on public.caja_cierres
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_caja_conteo_select on public.caja_conteos
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));
create policy abc_efecto_select on public.efectos_pendientes
  for select to authenticated using (private.la_tiene_local(empresa_id,local_id));

revoke all on public.terminales_tpv from anon;
revoke all on public.abc_operaciones from anon;
revoke all on public.abc_eventos from anon;
revoke all on public.cajas_fisicas from anon;
revoke all on public.caja_sesiones from anon;
revoke all on public.caja_sesion_terminales from anon;
revoke all on public.caja_cierres from anon;
revoke all on public.caja_conteos from anon;
revoke all on public.efectos_pendientes from anon;

revoke insert,update,delete on public.terminales_tpv from authenticated;
revoke insert,update,delete on public.abc_operaciones from authenticated;
revoke insert,update,delete on public.abc_eventos from authenticated;
revoke insert,update,delete on public.cajas_fisicas from authenticated;
revoke insert,update,delete on public.caja_sesiones from authenticated;
revoke insert,update,delete on public.caja_sesion_terminales from authenticated;
revoke insert,update,delete on public.caja_cierres from authenticated;
revoke insert,update,delete on public.caja_conteos from authenticated;
revoke insert,update,delete on public.efectos_pendientes from authenticated;

grant select on public.terminales_tpv to authenticated;
grant select on public.cajas_fisicas to authenticated;
grant select on public.caja_sesiones to authenticated;
grant select on public.caja_sesion_terminales to authenticated;
grant select on public.caja_cierres to authenticated;
grant select on public.caja_conteos to authenticated;

-- Deliberadamente sin GRANT SELECT directo en M01:
-- abc_operaciones, abc_eventos y efectos_pendientes.
