-- PM-07 · Stock y reversos por ubicación
-- Fuente: esquema vivo validado en L&A Suite QA.
-- Base funcional: PM-06 cerrado. No aplicar a producción sin autorización expresa.

create table if not exists public.stock_ubicacion (
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  almacen numeric(18,6) not null default 0 check (almacen >= 0),
  piso numeric(18,6) not null default 0 check (piso >= 0),
  minimo numeric(18,6) not null default 0 check (minimo >= 0),
  fraccionable boolean not null default false,
  precision_cantidad smallint not null default 0 check (precision_cantidad >= 0 and precision_cantidad <= 6),
  updated_at timestamptz not null default now(),
  local_operable boolean not null default true,
  primary key (empresa_id, local_id, producto_id)
);

create table if not exists public.stock_operaciones (
  operation_id text primary key,
  tipo text not null check (tipo in ('VENTA','REVERSO','TRASLADO_INTERNO')),
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  payload jsonb not null,
  actor_user_id uuid not null,
  ref_operation_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.movimientos_stock (
  id bigint generated by default as identity primary key,
  operation_id text not null references public.stock_operaciones(operation_id) on delete restrict,
  tipo text not null check (tipo in ('VENTA','REVERSO','TRASLADO_INTERNO')),
  empresa_id text not null,
  local_id text not null,
  producto_id text not null,
  delta_almacen numeric(18,6) not null,
  delta_piso numeric(18,6) not null,
  delta_total numeric(18,6) not null,
  cantidad numeric(18,6) not null check (cantidad > 0),
  movimiento_original_id bigint references public.movimientos_stock(id) on delete restrict,
  datos jsonb not null default '{}'::jsonb,
  actor_user_id uuid not null,
  created_at timestamptz not null default now(),
  constraint pm07_delta_total_consistente check (round(delta_total,6)=round(delta_almacen+delta_piso,6))
);

create index if not exists pm07_mov_stock_scope
  on public.movimientos_stock(empresa_id,local_id,producto_id,created_at);
create unique index if not exists pm07_un_reverso_por_movimiento
  on public.movimientos_stock(movimiento_original_id)
  where tipo='REVERSO' and movimiento_original_id is not null;

alter table public.stock_ubicacion enable row level security;
alter table public.stock_operaciones enable row level security;
alter table public.movimientos_stock enable row level security;

drop policy if exists pm07_stock_select on public.stock_ubicacion;
create policy pm07_stock_select on public.stock_ubicacion
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));

drop policy if exists pm07_operaciones_select on public.stock_operaciones;
create policy pm07_operaciones_select on public.stock_operaciones
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));

drop policy if exists pm07_movimientos_select on public.movimientos_stock;
create policy pm07_movimientos_select on public.movimientos_stock
  for select to authenticated
  using (private.la_tiene_local(empresa_id,local_id));

revoke insert, update, delete on public.stock_ubicacion from authenticated;
revoke insert, update, delete on public.stock_operaciones from authenticated;
revoke insert, update, delete on public.movimientos_stock from authenticated;
grant select on public.stock_ubicacion, public.stock_operaciones, public.movimientos_stock to authenticated;

create or replace view public.stock_estado as
select empresa_id,
       local_id,
       producto_id,
       almacen,
       piso,
       round(almacen+piso,6) as total,
       minimo,
       round(almacen+piso,6) < minimo as bajo_minimo,
       fraccionable,
       precision_cantidad,
       updated_at,
       local_operable
from public.stock_ubicacion;

grant select on public.stock_estado to authenticated;

create or replace function private.pm07_validar_cantidad(
  p_cantidad numeric,
  p_fraccionable boolean,
  p_precision smallint
) returns numeric
language plpgsql
immutable
set search_path='pg_catalog','pg_temp'
as $$
declare v numeric;
begin
  v := round(coalesce(p_cantidad,0), greatest(0,least(6,coalesce(p_precision,0))));
  if v <= 0 then raise exception 'cantidad_invalida'; end if;
  if not coalesce(p_fraccionable,false) and v <> trunc(v) then raise exception 'unidad_indivisible'; end if;
  if p_cantidad <> v then raise exception 'precision_cantidad_excedida'; end if;
  return v;
end;
$$;

create or replace function private.pm07_puede_gestionar_stock()
returns boolean
language sql
stable security definer
set search_path='public','auth','private','pg_temp'
as $$
  select private.la_usuario_activo()
     and coalesce(private.la_rol(),'') in ('Propietario','Encargado');
$$;

create or replace function private.pm07_puede_vender()
returns boolean
language sql
stable security definer
set search_path='public','auth','private','pg_temp'
as $$
  select private.la_usuario_activo()
     and coalesce(private.la_rol(),'') in ('Propietario','Encargado','Cajero/a','Camarero/a','Churrero/a');
$$;

create or replace function public.registrar_venta_stock(
  p_operation_id text,
  p_empresa_id text,
  p_local_id text,
  p_producto_id text,
  p_cantidad numeric,
  p_datos jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path='public','auth','private','pg_temp'
as $$
declare
  s public.stock_ubicacion%rowtype;
  op public.stock_operaciones%rowtype;
  payload_norm jsonb;
  cant numeric;
  tomar_piso numeric;
  tomar_almacen numeric;
  mov public.movimientos_stock%rowtype;
begin
  if auth.uid() is null or not private.pm07_puede_vender() then raise exception 'stock_no_autorizado'; end if;
  if not private.la_tiene_empresa(p_empresa_id) or not private.la_tiene_local(p_empresa_id,p_local_id) then raise exception 'contexto_no_autorizado'; end if;
  if p_operation_id is null or btrim(p_operation_id)='' then raise exception 'operation_id_requerido'; end if;

  select * into s from public.stock_ubicacion
   where empresa_id=p_empresa_id and local_id=p_local_id and producto_id=p_producto_id
   for update;
  if not found then raise exception 'stock_no_configurado'; end if;
  if not s.local_operable then raise exception 'local_inactivo'; end if;

  cant:=private.pm07_validar_cantidad(p_cantidad,s.fraccionable,s.precision_cantidad);
  payload_norm:=jsonb_build_object('empresaId',p_empresa_id,'localId',p_local_id,'productoId',p_producto_id,'cantidad',cant,'datos',coalesce(p_datos,'{}'::jsonb));

  select * into op from public.stock_operaciones where operation_id=p_operation_id;
  if found then
    if op.tipo='VENTA' and op.payload=payload_norm then
      select * into mov from public.movimientos_stock where operation_id=p_operation_id limit 1;
      return jsonb_build_object('ok',true,'replayed',true,'movimiento',to_jsonb(mov));
    end if;
    raise exception 'operation_id_conflict';
  end if;

  if round(s.almacen+s.piso,6)<cant then raise exception 'stock_insuficiente'; end if;
  tomar_piso:=least(s.piso,cant);
  tomar_almacen:=cant-tomar_piso;

  update public.stock_ubicacion
     set piso=piso-tomar_piso, almacen=almacen-tomar_almacen, updated_at=now()
   where empresa_id=p_empresa_id and local_id=p_local_id and producto_id=p_producto_id;

  insert into public.stock_operaciones(operation_id,tipo,empresa_id,local_id,producto_id,payload,actor_user_id)
  values(p_operation_id,'VENTA',p_empresa_id,p_local_id,p_producto_id,payload_norm,auth.uid());

  insert into public.movimientos_stock(operation_id,tipo,empresa_id,local_id,producto_id,delta_almacen,delta_piso,delta_total,cantidad,datos,actor_user_id)
  values(p_operation_id,'VENTA',p_empresa_id,p_local_id,p_producto_id,-tomar_almacen,-tomar_piso,-cant,cant,coalesce(p_datos,'{}'::jsonb),auth.uid())
  returning * into mov;

  return jsonb_build_object('ok',true,'replayed',false,'movimiento',to_jsonb(mov),'saldo',jsonb_build_object('almacen',s.almacen-tomar_almacen,'piso',s.piso-tomar_piso,'total',s.almacen+s.piso-cant));
end;
$$;

create or replace function public.revertir_venta_stock(
  p_operation_id text,
  p_venta_operation_id text,
  p_motivo text default null
) returns jsonb
language plpgsql
security definer
set search_path='public','auth','private','pg_temp'
as $$
declare
  original public.movimientos_stock%rowtype;
  op public.stock_operaciones%rowtype;
  mov public.movimientos_stock%rowtype;
  payload_norm jsonb;
begin
  if auth.uid() is null or not private.pm07_puede_gestionar_stock() then raise exception 'reverso_no_autorizado'; end if;
  if p_operation_id is null or btrim(p_operation_id)='' then raise exception 'operation_id_requerido'; end if;

  select m.* into original from public.movimientos_stock m
   where m.operation_id=p_venta_operation_id and m.tipo='VENTA'
   for update;
  if not found then raise exception 'venta_stock_no_encontrada'; end if;
  if not private.la_tiene_local(original.empresa_id,original.local_id) then raise exception 'contexto_no_autorizado'; end if;

  payload_norm := jsonb_build_object('ventaOperationId',p_venta_operation_id,'motivo',coalesce(p_motivo,''));
  select * into op from public.stock_operaciones where operation_id=p_operation_id;
  if found then
    if op.tipo='REVERSO' and op.payload=payload_norm then
      select * into mov from public.movimientos_stock where operation_id=p_operation_id limit 1;
      return jsonb_build_object('ok',true,'replayed',true,'movimiento',to_jsonb(mov));
    end if;
    raise exception 'operation_id_conflict';
  end if;

  if exists(select 1 from public.movimientos_stock where tipo='REVERSO' and movimiento_original_id=original.id) then raise exception 'venta_stock_ya_revertida'; end if;

  perform 1 from public.stock_ubicacion
   where empresa_id=original.empresa_id and local_id=original.local_id and producto_id=original.producto_id
   for update;
  if not found then raise exception 'stock_no_configurado'; end if;

  update public.stock_ubicacion
     set almacen=almacen-original.delta_almacen,
         piso=piso-original.delta_piso,
         updated_at=now()
   where empresa_id=original.empresa_id and local_id=original.local_id and producto_id=original.producto_id;

  insert into public.stock_operaciones(operation_id,tipo,empresa_id,local_id,producto_id,payload,actor_user_id,ref_operation_id)
  values(p_operation_id,'REVERSO',original.empresa_id,original.local_id,original.producto_id,payload_norm,auth.uid(),p_venta_operation_id);

  insert into public.movimientos_stock(operation_id,tipo,empresa_id,local_id,producto_id,delta_almacen,delta_piso,delta_total,cantidad,movimiento_original_id,datos,actor_user_id)
  values(p_operation_id,'REVERSO',original.empresa_id,original.local_id,original.producto_id,-original.delta_almacen,-original.delta_piso,-original.delta_total,original.cantidad,original.id,jsonb_build_object('motivo',coalesce(p_motivo,'')),auth.uid())
  returning * into mov;

  return jsonb_build_object('ok',true,'replayed',false,'movimiento',to_jsonb(mov));
end;
$$;

create or replace function public.trasladar_stock_interno(
  p_operation_id text,
  p_empresa_id text,
  p_local_id text,
  p_producto_id text,
  p_origen text,
  p_destino text,
  p_cantidad numeric,
  p_datos jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path='public','auth','private','pg_temp'
as $$
declare
  s public.stock_ubicacion%rowtype;
  op public.stock_operaciones%rowtype;
  mov public.movimientos_stock%rowtype;
  payload_norm jsonb;
  cant numeric;
  da numeric:=0;
  dp numeric:=0;
begin
  if auth.uid() is null or not private.pm07_puede_gestionar_stock() then raise exception 'traslado_no_autorizado'; end if;
  if not private.la_tiene_local(p_empresa_id,p_local_id) then raise exception 'contexto_no_autorizado'; end if;
  if p_origen not in ('almacen','piso') or p_destino not in ('almacen','piso') or p_origen=p_destino then raise exception 'ubicacion_invalida'; end if;
  if p_operation_id is null or btrim(p_operation_id)='' then raise exception 'operation_id_requerido'; end if;

  select * into s from public.stock_ubicacion
   where empresa_id=p_empresa_id and local_id=p_local_id and producto_id=p_producto_id
   for update;
  if not found then raise exception 'stock_no_configurado'; end if;
  if not s.local_operable then raise exception 'local_inactivo'; end if;

  cant:=private.pm07_validar_cantidad(p_cantidad,s.fraccionable,s.precision_cantidad);
  payload_norm:=jsonb_build_object('empresaId',p_empresa_id,'localId',p_local_id,'productoId',p_producto_id,'origen',p_origen,'destino',p_destino,'cantidad',cant,'datos',coalesce(p_datos,'{}'::jsonb));

  select * into op from public.stock_operaciones where operation_id=p_operation_id;
  if found then
    if op.tipo='TRASLADO_INTERNO' and op.payload=payload_norm then
      select * into mov from public.movimientos_stock where operation_id=p_operation_id limit 1;
      return jsonb_build_object('ok',true,'replayed',true,'movimiento',to_jsonb(mov));
    end if;
    raise exception 'operation_id_conflict';
  end if;

  if p_origen='almacen' then
    if s.almacen<cant then raise exception 'stock_insuficiente_ubicacion'; end if;
    da:=-cant; dp:=cant;
  else
    if s.piso<cant then raise exception 'stock_insuficiente_ubicacion'; end if;
    dp:=-cant; da:=cant;
  end if;

  update public.stock_ubicacion
     set almacen=almacen+da,piso=piso+dp,updated_at=now()
   where empresa_id=p_empresa_id and local_id=p_local_id and producto_id=p_producto_id;

  insert into public.stock_operaciones(operation_id,tipo,empresa_id,local_id,producto_id,payload,actor_user_id)
  values(p_operation_id,'TRASLADO_INTERNO',p_empresa_id,p_local_id,p_producto_id,payload_norm,auth.uid());

  insert into public.movimientos_stock(operation_id,tipo,empresa_id,local_id,producto_id,delta_almacen,delta_piso,delta_total,cantidad,datos,actor_user_id)
  values(p_operation_id,'TRASLADO_INTERNO',p_empresa_id,p_local_id,p_producto_id,da,dp,0,cant,coalesce(p_datos,'{}'::jsonb),auth.uid())
  returning * into mov;

  return jsonb_build_object('ok',true,'replayed',false,'movimiento',to_jsonb(mov),'saldo',jsonb_build_object('almacen',s.almacen+da,'piso',s.piso+dp,'total',s.almacen+s.piso));
end;
$$;

revoke all on function public.registrar_venta_stock(text,text,text,text,numeric,jsonb) from public;
revoke all on function public.revertir_venta_stock(text,text,text) from public;
revoke all on function public.trasladar_stock_interno(text,text,text,text,text,text,numeric,jsonb) from public;
grant execute on function public.registrar_venta_stock(text,text,text,text,numeric,jsonb) to authenticated;
grant execute on function public.revertir_venta_stock(text,text,text) to authenticated;
grant execute on function public.trasladar_stock_interno(text,text,text,text,text,text,numeric,jsonb) to authenticated;
